### ISSUE TITLE
Using rescue reads 

### ISSUE THREAD

**Issue by RogerioRibeiro201505534** [nanoporetech/pychopper#42] opened 2020-09-16 15:59 UTC
Hi there! This was discussed in a previous issue, but I still had questions after reading through it.

I'm also using nanopore reads for transcriptomics analysis. For what I understood, the rescue_reads.fq are reads that had middle adaptors and were separated right? Why I should not use these when performing (re)annotation? What about quantification?

Also on a separate issue, after running the pychopper it seems small sequences (< 50bp) are still in the output (reads_full_length.fq) even though in appears that the length filtering is still being used. From the cmd output:

Output fragments failing length filter (length < 50): 0

I used the following comand:

`cdna_classifier.py P1F2Int.fastq P1F2Int.oriented.fastq -r P1F2Int_report.pdf -w P1F2Int_rescued_reads.fastq -S P1F2Int_stat.tsv -u P1F2Int_unclass_reads.fastq`

**Comment by ozgegizlenci** [comment] 2020-09-29 22:08
I would like to add an additional question to this question.
We will not be able to assign to the rescued reads to the barcodes since some might not have the adaptors for the demultiplexing. Is there any way to track which barcodes the rescued reads belong to in the multiplexed libraries?
Thank you

**Comment by bsipos** [comment] 2020-11-09 15:29
@RogerioRibeiro201505534 In principle you can use the rescue reads for both annotation and quantification, however, you might find that their quality is not as good as in the case of the reads in the main output.

Regarding the short sequences: could you please provide me with a length distribution of all (or just the "too short") sequences.

**Comment by bsipos** [comment] 2020-11-09 15:33
@ozgegizlenci Unfortunately I cannot provide a practical solution to this other than ignoring the fusion reads. Are they prevalent enough to pose a problem for your analysis?

**Comment by RogerioRibeiro201505534** [comment] 2020-11-10 10:37
@bsipos Hi. After talking with my advisor we endded up using the rescue reads for both the quantification and annotation. Can you explain why their quality might be worst? 

Regarding the short sequences, I have attached a fastqc report of one sample after running pychopper with the comand bellow, and cocatenating the main output and the rescue reads.  
`cdna_classifier.py P1F2Int.fastq P1F2Int.oriented.fastq -r P1F2Int_report.pdf -w P1F2Int_rescued_reads.fastq -S P1F2Int_stat.tsv -u P1F2Int_unclass_reads.fastq`

As you can see from the length distribution there are small reads (< 50bps) being keep in the output, even though there seems to be a lenght filter. 


[P1F2Int.all.oriented_fastqc.zip](https://github.com/nanoporetech/pychopper/files/5516583/P1F2Int.all.oriented_fastqc.zip)

**Comment by bsipos** [comment] 2020-11-10 13:26
@RogerioRibeiro201505534 I could not open the archive file you have attached. Could you please paste here some images separately for the main and the rescue reads to make debugging easier?

**Comment by RogerioRibeiro201505534** [comment] 2020-11-10 17:31
Here are screenshots from the fastqc report on both the main and rescue reads output, from the summary and the lenghts distribution.

main output: 
![sample_1_oriented_reads_summary](https://user-images.githubusercontent.com/56797817/98709411-407f5100-237a-11eb-89fd-b6d960f9ee4a.png)

![sample_1_oriented_read_len_distribution](https://user-images.githubusercontent.com/56797817/98709408-3f4e2400-237a-11eb-8cfd-a9bc9d516c2f.png)


Rescue reads

![sample_1_rescue_reads_summary](https://user-images.githubusercontent.com/56797817/98709413-4117e780-237a-11eb-90bf-8f148f01396f.png)

![sample_1_rescue_read_len_distribution](https://user-images.githubusercontent.com/56797817/98709412-407f5100-237a-11eb-9985-d8bfcb67c7e1.png)

**Comment by bsipos** [comment] 2020-11-11 15:09
@RogerioRibeiro201505534 Hi! I think the issue is that you did not specify a file for the short reads using `-l`. Could you please try again with that option specified?

**Closed** 2020-11-26 10:21 UTC
